version: '3.7'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    secrets:
      - db_user
      - db_password
    container_name: unified_app_container

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: webapp
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_user
      - db_password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

secrets:
  db_user:
    file: ./secrets/db_user
  db_password:
    file: ./secrets/db_password
